apiVersion: v1
kind: ServiceAccount
metadata:
  name: crowdaq-installer
  namespace: xibo
  labels:
    app.kubernetes.io/name: crowdaq-installer
    app.kubernetes.io/part-of: xibo-plugin
    app.kubernetes.io/component: gitops-installer
